---
- name: Retrieve secret from AWS Secrets Manager
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.aws

  tasks:
    - name: Get secret value
      community.aws.secretsmanager_secret:
        name: ansible_secret
        region: us-east-1
      register: secret_result

    - name: Show secret value
      ansible.builtin.debug:
        var: secret_result.secret_string
