---
- name: Retrieve secret from AWS Secrets Manager
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get secret value
      amazon.aws.aws_secret:
        name: ansible_secret
        region: us-east-1
      register: secret_result

    - name: Show secret value
      debug:
        var: secret_result.value
